import type { AccountCategory, AccountType, GstDefault } from './types.js';

export interface ChartAccountSeed {
  accountNumber: string;
  name: string;
  accountType: AccountType;
  category: AccountCategory;
  gstDefault: GstDefault;
  isSystem: boolean;
  description?: string;
}

/** Production-ready Australian Chart of Accounts seed. */
export const AUSTRALIAN_CHART_OF_ACCOUNTS: ChartAccountSeed[] = [
  // Assets
  {
    accountNumber: '1-1000',
    name: 'Cash at Bank',
    accountType: 'Asset',
    category: 'Current Asset',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '1-1010',
    name: 'Petty Cash',
    accountType: 'Asset',
    category: 'Current Asset',
    gstDefault: 'NONE',
    isSystem: false,
  },
  {
    accountNumber: '1-1200',
    name: 'Accounts Receivable',
    accountType: 'Asset',
    category: 'Current Asset',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '1-1300',
    name: 'Inventory',
    accountType: 'Asset',
    category: 'Current Asset',
    gstDefault: 'GST',
    isSystem: true,
  },
  {
    accountNumber: '1-1400',
    name: 'Prepayments',
    accountType: 'Asset',
    category: 'Current Asset',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '1-1500',
    name: 'GST Receivable',
    accountType: 'Asset',
    category: 'Current Asset',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '1-1600',
    name: 'Other Current Assets',
    accountType: 'Asset',
    category: 'Current Asset',
    gstDefault: 'NONE',
    isSystem: false,
  },
  {
    accountNumber: '1-2000',
    name: 'Plant & Equipment',
    accountType: 'Asset',
    category: 'Non-Current Asset',
    gstDefault: 'CAPITAL',
    isSystem: false,
  },
  {
    accountNumber: '1-2010',
    name: 'Accumulated Depreciation',
    accountType: 'Asset',
    category: 'Non-Current Asset',
    gstDefault: 'NONE',
    isSystem: true,
    description: 'Contra-asset for plant and equipment',
  },

  // Liabilities
  {
    accountNumber: '2-1000',
    name: 'Accounts Payable',
    accountType: 'Liability',
    category: 'Current Liability',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '2-1100',
    name: 'GST Payable',
    accountType: 'Liability',
    category: 'Current Liability',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '2-1200',
    name: 'PAYG Withholding',
    accountType: 'Liability',
    category: 'Current Liability',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '2-1300',
    name: 'Superannuation Payable',
    accountType: 'Liability',
    category: 'Current Liability',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '2-1400',
    name: 'Loans',
    accountType: 'Liability',
    category: 'Non-Current Liability',
    gstDefault: 'NONE',
    isSystem: false,
  },
  {
    accountNumber: '2-1500',
    name: 'Credit Cards',
    accountType: 'Liability',
    category: 'Current Liability',
    gstDefault: 'NONE',
    isSystem: false,
  },
  {
    accountNumber: '2-1600',
    name: 'Unearned Revenue',
    accountType: 'Liability',
    category: 'Current Liability',
    gstDefault: 'GST',
    isSystem: false,
  },

  // Equity
  {
    accountNumber: '3-1000',
    name: 'Owner Capital',
    accountType: 'Equity',
    category: 'Equity',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '3-1100',
    name: 'Retained Earnings',
    accountType: 'Equity',
    category: 'Equity',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '3-1200',
    name: 'Current Year Earnings',
    accountType: 'Equity',
    category: 'Equity',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '3-1300',
    name: 'Drawings',
    accountType: 'Equity',
    category: 'Equity',
    gstDefault: 'NONE',
    isSystem: true,
  },

  // Income
  {
    accountNumber: '4-1000',
    name: 'Sales',
    accountType: 'Income',
    category: 'Income',
    gstDefault: 'GST',
    isSystem: true,
  },
  {
    accountNumber: '4-1100',
    name: 'Service Income',
    accountType: 'Income',
    category: 'Income',
    gstDefault: 'GST',
    isSystem: true,
  },
  {
    accountNumber: '4-1200',
    name: 'Interest Income',
    accountType: 'Income',
    category: 'Income',
    gstDefault: 'GST_FREE',
    isSystem: false,
  },
  {
    accountNumber: '4-1300',
    name: 'Other Income',
    accountType: 'Income',
    category: 'Income',
    gstDefault: 'GST',
    isSystem: false,
  },

  // Cost of Sales
  {
    accountNumber: '5-1000',
    name: 'Purchases',
    accountType: 'CostOfSales',
    category: 'Cost of Sales',
    gstDefault: 'GST',
    isSystem: true,
  },
  {
    accountNumber: '5-1100',
    name: 'Freight In',
    accountType: 'CostOfSales',
    category: 'Cost of Sales',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '5-1200',
    name: 'Inventory Adjustments',
    accountType: 'CostOfSales',
    category: 'Cost of Sales',
    gstDefault: 'GST',
    isSystem: true,
  },

  // Expenses
  {
    accountNumber: '6-1000',
    name: 'Advertising',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1010',
    name: 'Bank Fees',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST_FREE',
    isSystem: false,
  },
  {
    accountNumber: '6-1020',
    name: 'Insurance',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1030',
    name: 'Internet',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1040',
    name: 'Motor Vehicle',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1050',
    name: 'Office Expenses',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1060',
    name: 'Postage',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1070',
    name: 'Printing',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1080',
    name: 'Rent',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1090',
    name: 'Repairs',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1100',
    name: 'Software',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1110',
    name: 'Telephone',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1120',
    name: 'Travel',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1130',
    name: 'Utilities',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'GST',
    isSystem: false,
  },
  {
    accountNumber: '6-1140',
    name: 'Wages',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '6-1150',
    name: 'Super Expense',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '6-1160',
    name: 'Payroll Tax',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'NONE',
    isSystem: false,
  },
  {
    accountNumber: '6-1170',
    name: 'Depreciation',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'NONE',
    isSystem: true,
  },
  {
    accountNumber: '6-1180',
    name: 'GST Adjustments',
    accountType: 'Expense',
    category: 'Expense',
    gstDefault: 'NONE',
    isSystem: true,
  },
];

export const SYSTEM_ACCOUNT_NUMBERS = new Set(
  AUSTRALIAN_CHART_OF_ACCOUNTS.filter((account) => account.isSystem).map(
    (account) => account.accountNumber,
  ),
);
