import { describe, expect, it } from 'vitest';

import { extractPdfText } from '../helpers/pdf-text.js';
import {
  contentBottomLimit,
  formatAustralianAbn,
  formatAustralianDate,
  formatAustralianPhone,
  formatInvoiceNumberForPdf,
  PDF_PAGE_MARGIN,
  prepareBusinessNameForPdf,
} from '../../src/services/invoice-pdf-layout.js';
import { generateInvoicePdfBuffer } from '../../src/services/pdf-service.js';
import PDFDocument from 'pdfkit';

const profile = {
  id: 'business-profile',
  companyName: 'QUANTUM HIRE SERVICES PTY LTD',
  legalName: 'QUANTUM HIRE SERVICES PTY LTD',
  abnTaxId: '26641770130',
  address: '44 Harris Street Guildford NSW 2161',
  email: 'info@quantumhireservices.com.au',
  phone: '+61410760760',
  logoReference: null,
  primaryColor: '#173f35',
  secondaryColor: '#c4f36b',
  updatedAt: '2026-07-18T00:00:00.000Z',
};

const baseInput = {
  invoice: {
    id: 'inv-1',
    customerId: 'cus-1',
    title: 'Labour Hire',
    issueDate: '2026-07-23',
    dueDate: '2026-08-06',
    notes: 'Thanks for your business.',
    paymentTerms: 'Payment due within 14 days',
    invoiceNumber: '108',
    status: 'Finalised' as const,
    paymentState: 'Awaiting Payment' as const,
    reminderState: 'None' as const,
    totals: { subtotal: 1000.5, gstTotal: 100.05, total: 1100.55 },
    createdAt: '2026-07-18T00:00:00.000Z',
    updatedAt: '2026-07-18T00:00:00.000Z',
  },
  lineItems: [
    {
      description: 'Labour hire services',
      quantity: 1,
      unitPrice: 1000.5,
      gstApplicable: true,
    },
  ],
  customer: {
    id: 'cus-1',
    displayName: 'Site Co',
    email: 'site@example.com',
    phone: null,
    address: '9 Build St',
    abnTaxId: null,
    notes: null,
    createdAt: '2026-07-18T00:00:00.000Z',
    updatedAt: '2026-07-18T00:00:00.000Z',
  },
  businessProfile: profile,
};

function assertNoGeneratedByFooter(text: string): void {
  expect(text).not.toContain('Generated by Aleya Invoicing');
  expect(text).not.toContain('Generated by Aboss');
  expect(text).not.toMatch(/Generated by Aleya Invoicing\s*·\s*G/);
  expect(text).not.toMatch(/Generated by Aleya/i);
  expect(text).not.toMatch(/Generated by Aboss/i);
}

function assertNoGstRegistrationLabels(text: string): void {
  expect(text).not.toContain('GST status:');
  expect(text).not.toContain('GST Registered');
  expect(text).not.toContain('GST registered - GST shown per line');
  expect(text).not.toContain('No GST charged on this invoice');
}

describe('invoice PDF formatting helpers', () => {
  it('formats Australian mobile numbers in readable international form', () => {
    expect(formatAustralianPhone('+61410760760')).toBe('+61 410 760 760');
    expect(formatAustralianPhone('0410760760')).toBe('+61 410 760 760');
    expect(formatAustralianPhone('61410760760')).toBe('+61 410 760 760');
  });

  it('formats ISO dates as DD/MM/YYYY', () => {
    expect(formatAustralianDate('2026-07-23')).toBe('23/07/2026');
    expect(formatAustralianDate('2026-08-06')).toBe('06/08/2026');
  });

  it('formats ABN with grouping spaces', () => {
    expect(formatAustralianAbn('26641770130')).toBe('26 641 770 130');
    expect(formatAustralianAbn('26 641 770 130')).toBe('26 641 770 130');
  });

  it('keeps Pty Ltd suffix attached for wrapping', () => {
    const prepared = prepareBusinessNameForPdf('QUANTUM HIRE SERVICES PTY LTD');
    expect(prepared).toContain('\u00A0PTY\u00A0LTD');
    expect(prepared.replace(/\u00A0/g, ' ')).toBe('QUANTUM HIRE SERVICES PTY LTD');
  });

  it('maps draft vs assigned invoice numbers for PDF metadata', () => {
    expect(formatInvoiceNumberForPdf(null)).toEqual({
      statusLine: 'Status: Draft',
      invoiceNumberLine: 'Invoice Number: Not assigned',
    });
    expect(formatInvoiceNumberForPdf('108')).toEqual({
      statusLine: null,
      invoiceNumberLine: 'Invoice Number: 108',
    });
  });
});

describe('invoice PDF branding & layout polish', () => {
  it('renders invoice 108 acceptance header and metadata', async () => {
    const pdf = await generateInvoicePdfBuffer(baseInput);
    const text = extractPdfText(pdf);

    expect(text).toContain('QUANTUM HIRE SERVICES PTY LTD');
    expect(text).toContain('44 Harris Street Guildford NSW 2161');
    expect(text).toContain('ABN: 26 641 770 130');
    expect(text).toContain('Email: info@quantumhireservices.com.au');
    expect(text).toContain('Phone: +61 410 760 760');
    expect(text).toContain('TAX INVOICE');
    expect(text).toContain('Invoice Number: 108');
    expect(text).toContain('Issue Date: 23/07/2026');
    expect(text).toContain('Due Date: 06/08/2026');
    expect(text).toContain('Title: Labour Hire');

    expect(text).not.toContain('Invoice Number: Draft');
    expect(text).not.toContain('Invoice Number: Not assigned');
    expect(text).not.toContain('Title: Invoice #108');
    expect(text).not.toContain('2026-07-23');
    expect(text).not.toContain('2026-08-06');
    expect(text).not.toContain('+61410760760');
    assertNoGstRegistrationLabels(text);
    assertNoGeneratedByFooter(text);

    // Business name must not orphan PTY LTD onto its own extracted line when space allows.
    expect(text).not.toMatch(/SERVICES\s*\n\s*PTY LTD/i);
  });

  it('renders draft invoices with Status Draft and Not assigned number', async () => {
    const pdf = await generateInvoicePdfBuffer({
      ...baseInput,
      invoice: {
        ...baseInput.invoice,
        title: 'Scaffold hire',
        invoiceNumber: null,
        status: 'Draft',
        paymentState: 'Draft',
      },
    });
    const text = extractPdfText(pdf);
    expect(text).toContain('Status: Draft');
    expect(text).toContain('Invoice Number: Not assigned');
    expect(text).toContain('Title: Scaffold hire');
    expect(text).not.toContain('Invoice Number: Draft');
    expect(text).not.toContain('Title: Invoice #');
    assertNoGstRegistrationLabels(text);
    assertNoGeneratedByFooter(text);
  });

  it('keeps title separate from invoice number and never invents Invoice # title', async () => {
    const pdf = await generateInvoicePdfBuffer(baseInput);
    const text = extractPdfText(pdf);
    expect(text).toContain('Invoice Number: 108');
    expect(text).toContain('Title: Labour Hire');
    expect(text).not.toMatch(/Title:\s*Invoice\s*#\s*108/i);
  });

  it('labels payment email as Email, never Accounts', async () => {
    const pdf = await generateInvoicePdfBuffer(baseInput);
    const text = extractPdfText(pdf);
    expect(text).toContain('Email: info@quantumhireservices.com.au');
    expect(text).not.toMatch(/Accounts:\s*info@quantumhireservices\.com\.au/);
    expect(text).not.toContain('Accounts:');
  });

  it('omits all generated-by branding footers (Aleya and Aboss)', async () => {
    const pdf = await generateInvoicePdfBuffer(baseInput);
    const text = extractPdfText(pdf);
    assertNoGeneratedByFooter(text);
    expect(text).toContain('Payment details');
    expect(text).toContain('Email: info@quantumhireservices.com.au');
  });

  it('does not reserve empty footer band after footer removal', () => {
    const doc = new PDFDocument({ size: 'A4', margin: PDF_PAGE_MARGIN });
    expect(contentBottomLimit(doc)).toBe(doc.page.height - PDF_PAGE_MARGIN);
    doc.end();
  });

  it('renders decimal-aligned totals labels and amounts', async () => {
    const pdf = await generateInvoicePdfBuffer(baseInput);
    const text = extractPdfText(pdf);
    expect(text).toContain('Subtotal');
    expect(text).toContain('1000.50');
    expect(text).toContain('GST');
    expect(text).toContain('100.05');
    expect(text).toContain('Total');
    expect(text).toContain('1100.55');
    assertNoGstRegistrationLabels(text);
    assertNoGeneratedByFooter(text);
  });

  it('renders optional bank transfer details separately from email', async () => {
    const pdf = await generateInvoicePdfBuffer({
      ...baseInput,
      bankDetails: {
        bankName: 'Example Bank',
        bsb: '062-000',
        accountNumber: '12345678',
        accountName: 'Quantum Hire Services',
      },
    });
    const text = extractPdfText(pdf);
    expect(text).toContain('Email: info@quantumhireservices.com.au');
    expect(text).toContain('Bank transfer');
    expect(text).toContain('Bank: Example Bank');
    expect(text).toContain('BSB: 062-000');
    expect(text).toContain('Account Number: 12345678');
    expect(text).toContain('Account Name: Quantum Hire Services');
    assertNoGeneratedByFooter(text);
  });

  it('keeps A4, Letter and multi-page PDFs aligned without branding footers', async () => {
    const manyLines = Array.from({ length: 40 }, (_, index) => ({
      description: `Line item ${index + 1} with enough text to force wrapping and pagination`,
      quantity: 1,
      unitPrice: 10 + index,
      gstApplicable: true,
    }));
    const multiPageInput = {
      ...baseInput,
      lineItems: manyLines,
      invoice: {
        ...baseInput.invoice,
        totals: {
          subtotal: manyLines.reduce((sum, item) => sum + item.unitPrice, 0),
          gstTotal: manyLines.reduce((sum, item) => sum + item.unitPrice * 0.1, 0),
          total: manyLines.reduce((sum, item) => sum + item.unitPrice * 1.1, 0),
        },
      },
    };

    const a4 = await generateInvoicePdfBuffer({ ...baseInput, pageSize: 'A4' });
    const letter = await generateInvoicePdfBuffer({ ...baseInput, pageSize: 'LETTER' });
    const multi = await generateInvoicePdfBuffer({ ...multiPageInput, pageSize: 'A4' });

    expect(a4.subarray(0, 5).toString('utf8')).toBe('%PDF-');
    expect(letter.subarray(0, 5).toString('utf8')).toBe('%PDF-');
    expect(multi.subarray(0, 5).toString('utf8')).toBe('%PDF-');
    expect(multi.length).toBeGreaterThan(a4.length);

    for (const pdf of [a4, letter, multi]) {
      const text = extractPdfText(pdf);
      expect(text).toContain('Email: info@quantumhireservices.com.au');
      expect(text).toContain('Payment details');
      expect(text).toContain('Subtotal');
      expect(text).toContain('Total');
      assertNoGstRegistrationLabels(text);
      assertNoGeneratedByFooter(text);
    }
  });
});
