import { describe, expect, it } from 'vitest';

import { extractPdfText } from '../helpers/pdf-text.js';
import {
  contentBottomLimit,
  gstStatusLabel,
  PDF_PAGE_MARGIN,
} from '../../src/services/invoice-pdf-layout.js';
import { generateInvoicePdfBuffer } from '../../src/services/pdf-service.js';
import PDFDocument from 'pdfkit';

const profile = {
  id: 'business-profile',
  companyName: 'Quantum Hire Services With A Very Long Trading Name Pty Ltd',
  legalName: 'Quantum Hire Services Pty Ltd',
  abnTaxId: '12345678901',
  address: '1 Scaffold Way Sydney NSW 2000',
  email: 'info@company.com.au',
  phone: '0400000000',
  logoReference: null,
  primaryColor: '#173f35',
  secondaryColor: '#c4f36b',
  updatedAt: '2026-07-18T00:00:00.000Z',
};

const baseInput = {
  invoice: {
    id: 'inv-1',
    customerId: 'cus-1',
    title: 'Scaffold hire',
    issueDate: '2026-07-18',
    dueDate: '2026-08-01',
    notes: 'Thanks for your business.',
    paymentTerms: 'Payment due within 14 days',
    invoiceNumber: 'INV-1001',
    status: 'Finalised' as const,
    paymentState: 'Awaiting Payment' as const,
    reminderState: 'None' as const,
    totals: { subtotal: 1000.5, gstTotal: 100.05, total: 1100.55 },
    createdAt: '2026-07-18T00:00:00.000Z',
    updatedAt: '2026-07-18T00:00:00.000Z',
  },
  lineItems: [
    {
      description: 'Tower section',
      quantity: 1,
      unitPrice: 1000.5,
      gstApplicable: true,
    },
  ],
  customer: {
    id: 'cus-1',
    displayName: 'Site Co',
    email: 'site@example.com',
    phone: null,
    address: '9 Build St',
    abnTaxId: null,
    notes: null,
    createdAt: '2026-07-18T00:00:00.000Z',
    updatedAt: '2026-07-18T00:00:00.000Z',
  },
  businessProfile: profile,
};

function assertNoGeneratedByFooter(text: string): void {
  expect(text).not.toContain('Generated by Aleya Invoicing');
  expect(text).not.toContain('Generated by Aboss');
  expect(text).not.toMatch(/Generated by Aleya Invoicing\s*·\s*G/);
  expect(text).not.toMatch(/Generated by Aleya/i);
  expect(text).not.toMatch(/Generated by Aboss/i);
}

describe('invoice PDF branding & layout polish', () => {
  it('labels payment email as Email, never Accounts', async () => {
    const pdf = await generateInvoicePdfBuffer(baseInput);
    const text = extractPdfText(pdf);
    expect(text).toContain('Email: info@company.com.au');
    expect(text).not.toMatch(/Accounts:\s*info@company\.com\.au/);
    expect(text).not.toContain('Accounts:');
  });

  it('uses the business profile for company, ABN, email, phone, address and GST status', async () => {
    const pdf = await generateInvoicePdfBuffer(baseInput);
    const text = extractPdfText(pdf);
    expect(text).toContain('Quantum Hire Services With A Very Long Trading Name Pty Ltd');
    expect(text).toContain('ABN: 12345678901');
    expect(text).toContain('info@company.com.au');
    expect(text).toContain('0400000000');
    expect(text).toContain('1 Scaffold Way Sydney NSW 2000');
    expect(text).toContain('GST status: GST registered - GST shown per line');
  });

  it('omits all generated-by branding footers (Aleya and Aboss)', async () => {
    const pdf = await generateInvoicePdfBuffer(baseInput);
    const text = extractPdfText(pdf);
    assertNoGeneratedByFooter(text);
    // Ends with payment / business contact info, not a branding footer.
    expect(text).toContain('Payment details');
    expect(text).toContain('Email: info@company.com.au');
  });

  it('does not reserve empty footer band after footer removal', () => {
    const doc = new PDFDocument({ size: 'A4', margin: PDF_PAGE_MARGIN });
    // Content may use the full printable area down to the standard bottom margin.
    expect(contentBottomLimit(doc)).toBe(doc.page.height - PDF_PAGE_MARGIN);
    doc.end();
  });

  it('renders decimal-aligned totals labels and amounts', async () => {
    const pdf = await generateInvoicePdfBuffer(baseInput);
    const text = extractPdfText(pdf);
    expect(text).toContain('Subtotal');
    expect(text).toContain('1000.50');
    expect(text).toContain('GST');
    expect(text).toContain('100.05');
    expect(text).toContain('Total');
    expect(text).toContain('1100.55');
    assertNoGeneratedByFooter(text);
  });

  it('renders optional bank transfer details separately from email', async () => {
    const pdf = await generateInvoicePdfBuffer({
      ...baseInput,
      bankDetails: {
        bankName: 'Example Bank',
        bsb: '062-000',
        accountNumber: '12345678',
        accountName: 'Quantum Hire Services',
      },
    });
    const text = extractPdfText(pdf);
    expect(text).toContain('Email: info@company.com.au');
    expect(text).toContain('Bank transfer');
    expect(text).toContain('Bank: Example Bank');
    expect(text).toContain('BSB: 062-000');
    expect(text).toContain('Account Number: 12345678');
    expect(text).toContain('Account Name: Quantum Hire Services');
    assertNoGeneratedByFooter(text);
  });

  it('keeps A4, Letter and multi-page PDFs aligned without branding footers', async () => {
    const manyLines = Array.from({ length: 40 }, (_, index) => ({
      description: `Line item ${index + 1} with enough text to force wrapping and pagination`,
      quantity: 1,
      unitPrice: 10 + index,
      gstApplicable: true,
    }));
    const multiPageInput = {
      ...baseInput,
      lineItems: manyLines,
      invoice: {
        ...baseInput.invoice,
        totals: {
          subtotal: manyLines.reduce((sum, item) => sum + item.unitPrice, 0),
          gstTotal: manyLines.reduce((sum, item) => sum + item.unitPrice * 0.1, 0),
          total: manyLines.reduce((sum, item) => sum + item.unitPrice * 1.1, 0),
        },
      },
    };

    const a4 = await generateInvoicePdfBuffer({ ...baseInput, pageSize: 'A4' });
    const letter = await generateInvoicePdfBuffer({ ...baseInput, pageSize: 'LETTER' });
    const multi = await generateInvoicePdfBuffer({ ...multiPageInput, pageSize: 'A4' });

    expect(a4.subarray(0, 5).toString('utf8')).toBe('%PDF-');
    expect(letter.subarray(0, 5).toString('utf8')).toBe('%PDF-');
    expect(multi.subarray(0, 5).toString('utf8')).toBe('%PDF-');
    expect(multi.length).toBeGreaterThan(a4.length);

    for (const pdf of [a4, letter, multi]) {
      const text = extractPdfText(pdf);
      expect(text).toContain('Email: info@company.com.au');
      expect(text).toContain('Payment details');
      expect(text).toContain('Subtotal');
      expect(text).toContain('Total');
      assertNoGeneratedByFooter(text);
    }

    expect(gstStatusLabel([{ description: 'A', quantity: 1, unitPrice: 1, gstApplicable: false }])).toBe(
      'No GST charged on this invoice',
    );
  });
});
