import { describe, expect, it } from 'vitest';

import { isBusinessProfileReady } from '../../public/business-profile-readiness.js';
import { buildApp } from '../../src/app.js';
import { extractPdfText } from '../helpers/pdf-text.js';

describe('business profile unlock flow', () => {
  it('saves profile in Aleya DB and enables PDF generation with identity fields', async () => {
    const app = await buildApp({
      dbPath: ':memory:',
      nodeEnv: 'test',
      authBypassForTesting: true,
      serveFrontend: true,
    });

    const missing = await app.inject({ method: 'GET', url: '/api/business-profile' });
    expect(missing.statusCode).toBe(404);
    expect(isBusinessProfileReady(null)).toBe(false);

    const save = await app.inject({
      method: 'POST',
      url: '/api/business-profile',
      payload: {
        companyName: 'Aleya Hire Co',
        address: '1 Hire Road, Sydney NSW',
        abnTaxId: '12345678901',
        email: 'accounts@aleya.test',
        phone: '0400111222',
        primaryColor: '#173f35',
        secondaryColor: '#c4f36b',
      },
    });
    expect(save.statusCode).toBe(200);
    expect(isBusinessProfileReady(save.json())).toBe(true);

    const after = await app.inject({ method: 'GET', url: '/api/business-profile' });
    expect(after.statusCode).toBe(200);
    expect(after.json().companyName).toBe('Aleya Hire Co');
    expect(after.json().address).toBe('1 Hire Road, Sydney NSW');
    expect(after.json().abnTaxId).toBe('12345678901');

    const cust = await app.inject({ method: 'POST', url: '/api/customers', payload: { displayName: 'Site Co' } });
    const inv = await app.inject({
      method: 'POST',
      url: '/api/invoices',
      payload: {
        customerId: cust.json().id,
        title: 'Job',
        issueDate: '2026-07-18',
        dueDate: '2026-08-01',
        paymentTerms: '14 days',
        lineItems: [{ description: 'Labour', quantity: 1, unitPrice: 100, gstApplicable: true }],
      },
    });
    expect(inv.statusCode).toBe(201);

    const pdf = await app.inject({ method: 'GET', url: `/api/invoices/${inv.json().id}/pdf` });
    expect(pdf.statusCode).toBe(200);
    expect(pdf.headers['content-type']).toContain('application/pdf');
    const pdfBytes = Buffer.from(pdf.rawPayload);
    expect(pdfBytes.subarray(0, 4).toString()).toBe('%PDF');
    const pdfText = extractPdfText(pdfBytes);
    expect(pdfText).toContain('Aleya Hire Co');
    expect(pdfText).toContain('1 Hire Road, Sydney NSW');
    expect(pdfText).toContain('12345678901');
    expect(pdfText).toContain('accounts@aleya.test');
    expect(pdfText).toContain('0400111222');
    expect(pdfText).toContain('TAX INVOICE');
    expect(pdfText).toContain('Payment details');
    expect(pdfText).toContain('Generated by Aleya Invoicing');
    expect(pdfText).toContain('GST');

    const launch = await app.inject({ method: 'GET', url: '/assets/launch-app.js' });
    expect(launch.body).not.toContain('BUSINESS_PROFILE_NOT_FOUND');
    expect(launch.body).toContain('invalidateBusinessProfileCache');

    const readiness = await app.inject({ method: 'GET', url: '/assets/business-profile-readiness.js' });
    expect(readiness.statusCode).toBe(200);
    expect(readiness.body).toContain('isBusinessProfileReady');

    await app.close();
  });
});
