import { mkdtempSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';

import { afterEach, describe, expect, it } from 'vitest';

import { buildApp } from '../../src/app.js';
import { extractPdfText } from '../helpers/pdf-text.js';
import { createCartNTipReferenceDesign } from '../../src/domain/templates/cart-n-tip-reference.js';

const apps: Array<{ close: () => Promise<void> }> = [];

afterEach(async () => {
  while (apps.length) {
    const app = apps.pop();
    if (app) await app.close();
  }
});

function tempDbPath() {
  return join(mkdtempSync(join(tmpdir(), 'cart-n-tip-')), 'app.db');
}

describe('Cart N Tip #107 Quantum Hire recreation', () => {
  it('installs reference template and exports a matching Quantum Hire PDF', async () => {
    const app = await buildApp({
      dbPath: tempDbPath(),
      authBypassForTesting: true,
      serveFrontend: true,
    });
    apps.push(app);

    const installed = await app.inject({
      method: 'POST',
      url: '/api/invoice-templates/install-reference',
      payload: {},
    });
    expect(installed.statusCode).toBe(201);
    const template = installed.json().template;
    expect(template.design.layout.layoutPreset).toBe('quantum-hire');
    expect(template.isDefault).toBe(true);
    expect(template.name).toMatch(/Quantum Hire/i);
    expect(template.design.bankDetails.bsb).toBe('012347');

    const customer = await app.inject({
      method: 'POST',
      url: '/api/customers',
      payload: {
        displayName: 'Cart and Tip Pty Ltd',
        email: 'accounts@cartntip.example',
      },
    });
    expect(customer.statusCode).toBe(201);

    const invoice = await app.inject({
      method: 'POST',
      url: '/api/invoices',
      payload: {
        customerId: customer.json().id,
        title: 'Labour Hire',
        issueDate: '2026-07-06',
        dueDate: '2026-07-13',
        paymentTerms: '7 Days',
        notes:
          'Payment is required within 7 days from the invoice date.\nThank you for your business.',
        templateId: template.id,
        lineItems: [
          {
            description: '29/06/2026 Labour Hire - Day Shift',
            quantity: 1,
            unitPrice: 350,
            gstApplicable: true,
          },
          {
            description: '30/06/2026 Labour Hire - Day Shift',
            quantity: 1,
            unitPrice: 350,
            gstApplicable: true,
          },
          {
            description: '01/07/2026 Labour Hire - Day Shift',
            quantity: 1,
            unitPrice: 350,
            gstApplicable: true,
          },
          {
            description: '02/07/2026 Labour Hire - Day Shift',
            quantity: 1,
            unitPrice: 350,
            gstApplicable: true,
          },
          {
            description: '03/07/2026 Labour Hire - Day Shift',
            quantity: 1,
            unitPrice: 350,
            gstApplicable: true,
          },
          {
            description: '03/07/2026 Labour Hire - Night Shift',
            quantity: 1,
            unitPrice: 350,
            gstApplicable: true,
          },
        ],
      },
    });
    expect(invoice.statusCode).toBe(201);

    const pdf = await app.inject({
      method: 'GET',
      url: `/api/invoices/${invoice.json().id}/pdf`,
    });
    expect(pdf.statusCode).toBe(200);
    const buf = Buffer.from(pdf.rawPayload);
    const outDir = '/opt/cursor/artifacts/cart-n-tip-reference';
    mkdirSync(outDir, { recursive: true });
    const outPdf = join(outDir, 'aleya-recreated-cart-n-tip-107.pdf');
    writeFileSync(outPdf, buf);
    try {
      execFileSync('pdftoppm', ['-png', '-r', '150', outPdf, join(outDir, 'aleya-recreated')], {
        stdio: 'pipe',
      });
    } catch {
      /* optional visual render */
    }

    const text = extractPdfText(buf);
    expect(text).toContain('TAX INVOICE');
    expect(text).toContain('BILL TO');
    expect(text).toContain('FROM');
    expect(text).toContain('Cart and Tip Pty Ltd');
    expect(text).toContain('Quantum Hire Services Pty Ltd');
    expect(text).toContain('DATE');
    expect(text).toContain('DESCRIPTION');
    expect(text).toContain('RATE');
    expect(text).toContain('AMOUNT (EX GST)');
    expect(text).toContain('29/06/2026');
    expect(text).toContain('Labour Hire - Day Shift');
    expect(text).toContain('Labour Hire - Night Shift');
    expect(text).toContain('012347');
    expect(text).toContain('814027296');
    expect(text).toContain('SUBTOTAL (EX GST)');
    expect(text).toContain('TOTAL (INC GST)');
    expect(text).toContain('PAYMENT DETAILS');
    expect(text).toContain('PLEASE NOTE');
    expect(text).not.toContain('Line Items');
    expect(text).not.toContain('Generated by Aleya');

    // Design fixture itself is stable
    expect(createCartNTipReferenceDesign().layout.layoutPreset).toBe('quantum-hire');

    // Keep reference PDF path documented for side-by-side
    expect(
      readFileSync(
        join(process.cwd(), 'tests/fixtures/reference-invoices/Cart_N_Tip_107.pdf'),
      ).length,
    ).toBeGreaterThan(1000);
  });
});
